// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://winzoengxmtviqgfthth.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpbnpvZW5neG10dmlxZ2Z0aHRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzExODE3NTgsImV4cCI6MjA0Njc1Nzc1OH0.3kmR5NQ0CpCmYZgYrBqQicV7CDqDUXuexXNdhTynHlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});